example:
  property: "BLOG"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ApplicationBlog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ENC(0w+N2ubVv+P2H6R2aBW+6w==)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
